package Main;

import java.io.IOException;
import java.io.StringReader;
import java.io.StringWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Main class with code to test the system.
 * @author J.Vedder S4379101 
 */
public class Qtrees {

    public static void main(String[] args) {
        
        //Make tree from string:
        String test_tekst = "10011010001010010001010101100011000101000000";
        StringReader input = new StringReader(test_tekst);
        QTree qt = new QTree( input );
        //Making string from tree:
        StringWriter sb = new StringWriter();
        try {
            qt.writeQTree(sb);
        } catch (IOException ex) {
            Logger.getLogger(Qtrees.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println();
        System.out.println(sb.toString());
        
        
        //Filling bitmap with tree generated by string:
        Bitmap bitmap = new Bitmap(8, 8);
        qt.fillBitmap( bitmap );
        qt = new QTree (bitmap);
        System.out.println(bitmap);
        
        //Generating string from tree generated via bitmap
        sb = new StringWriter();
        try {
            qt.writeQTree(sb);
        } catch (IOException ex) {
            Logger.getLogger(Qtrees.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println();
        System.out.println(sb.toString());
        
        //Generating bitmap from tree
        bitmap = new Bitmap(8, 8);
        qt.fillBitmap( bitmap );
        qt = new QTree (bitmap);
        System.out.println(bitmap);
    }
}
